services:
  backend:
    build: ./backend
    image: fdc-case7-backend
    container_name: fdc-case7-backend
    restart: unless-stopped
    ports:
      - 4001:3000
    volumes:
      - ./backend/env-docker.json:/app/env.json
      - ./backend/casbin.conf:/app/casbin.conf
      - ./backend/locale:/app/locale
      - ./backend/logs:/app/logs
      - ./backend/docs/swagger.json:/app/docs/swagger.json
    networks:
      - fdc
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_PUBLIC_KEY: ${NEXT_PUBLIC_PUBLIC_KEY}
        NEXT_PUBLIC_URL_ENDPOINT: ${NEXT_PUBLIC_URL_ENDPOINT}
        PRIVATE_KEY: ${PRIVATE_KEY}
        NEXT_PUBLIC_HOST_PERSON: ${NEXT_PUBLIC_HOST_PERSON}
        NEXT_PUBLIC_HOST_PRODUCT: ${NEXT_PUBLIC_HOST_PRODUCT}
        NEXT_PUBLIC_HOST_EXAMPLE: ${NEXT_PUBLIC_HOST_EXAMPLE}
    image: fdc-case7-frontend
    container_name: fdc-case7-frontend
    restart: unless-stopped
    ports:
      - 4000:3000
    networks:
      - fdc
    depends_on:
      - backend

networks:
  fdc:
    driver: bridge